<#
.SYNOPSIS
    Displays and follows a CMTrace-formatted log file.

.DESCRIPTION
    Reads a CMTrace-formatted log file, parses each entry, and displays it
    in a readable, color-coded format.

    Long messages are word-wrapped to the console width, with continuation
    lines indented to align under the message column instead of the
    terminal hard-wrapping mid-word at column 0. Wrapping is skipped when
    output is redirected (piped or captured to a file).

    After processing the existing lines, the script continues monitoring the
    file and displays new entries as they are written.

    CMTrace severity colors:

        Information = Gray
        Warning     = Yellow
        Error       = Red

.PARAMETER LogFile
    Specifies the path to the CMTrace-formatted log file.

    The file must exist when the script starts.

.PARAMETER Type
    Specifies the CMTrace severity types to display.

    Supported values:

        All
        Information
        Warning
        Error

    Multiple severity types can be provided by separating them with commas.

    The default value is All.

.PARAMETER Tail
    Specifies the number of existing physical lines to process when the
    script starts.

    After processing those lines, the script continues monitoring the file
    for new entries.

    If Tail is omitted, the entire existing log is processed.

    Tail is applied before parsing and filtering. For example, using
    "-Tail 100 -Type Error" examines the last 100 physical lines and displays
    only errors found within those lines.

.PARAMETER WhereObject
    Specifies an optional Where-Object filter script to apply to every parsed
    CMTrace entry.

    The current parsed entry is available through $_ and contains:

        Timestamp
        Date
        Time
        Component
        Context
        Type
        Severity
        Thread
        File
        Message

    Non-CMTrace lines are not displayed when WhereObject is specified.

.PARAMETER HideField
    Specifies which fields to omit from the displayed line.

    Supported values:

        Timestamp
        Component
        Severity
        Thread
        Message

    Multiple fields can be provided by separating them with commas.

    Hiding a field only affects what is displayed; filtering (via -Type or
    -WhereObject) is always applied first, against the full parsed entry, so
    a hidden field can still be filtered on. For example, "-WhereObject {
    $_.Severity -eq 'Error' } -HideField Severity" filters on severity while
    hiding the Severity field from the output.

    Any combination of fields can be hidden. The remaining, visible fields
    keep their normal left-to-right order (Timestamp, Component, Severity,
    Thread, Message).

.EXAMPLE
    .\Watch-CMTraceLog.ps1 `
        -LogFile 'C:\Windows\CCM\Logs\AppEnforce.log'

    Processes the entire existing log and follows new entries.

.EXAMPLE
    .\Watch-CMTraceLog.ps1 `
        -LogFile 'C:\Windows\CCM\Logs\AppEnforce.log' `
        -Tail 50

    Processes the last 50 physical lines and follows new entries.

.EXAMPLE
    .\Watch-CMTraceLog.ps1 `
        -LogFile 'C:\Windows\CCM\Logs\AppEnforce.log' `
        -Type Error

    Displays only error entries.

.EXAMPLE
    .\Watch-CMTraceLog.ps1 `
        -LogFile 'C:\Windows\CCM\Logs\AppEnforce.log' `
        -Tail 100 `
        -Type Warning, Error

    Examines the last 100 lines and displays warnings and errors.

.EXAMPLE
    .\Watch-CMTraceLog.ps1 `
        -LogFile 'C:\Windows\CCM\Logs\AppEnforce.log' `
        -WhereObject { $_.Component -eq 'AppEnforce' }

    Displays entries generated by the AppEnforce component.

.EXAMPLE
    .\Watch-CMTraceLog.ps1 `
        -LogFile 'C:\Windows\CCM\Logs\AppEnforce.log' `
        -WhereObject { $_.Message -match 'failed|error|exception' }

    Displays entries whose message matches the supplied regular expression.

.EXAMPLE
    .\Watch-CMTraceLog.ps1 `
        -LogFile 'C:\Windows\CCM\Logs\AppEnforce.log' `
        -Tail 500 `
        -WhereObject {
            $_.Severity -in 'Warning', 'Error' -and
            $_.Message -match 'install'
        }

    Displays warning and error entries containing "install" from the last
    500 lines and from new entries written afterward.

.EXAMPLE
    .\Watch-CMTraceLog.ps1 `
        -LogFile 'C:\Windows\CCM\Logs\AppEnforce.log' `
        -WhereObject { $_.Severity -eq 'Error' } `
        -HideField Severity, Thread

    Filters on error severity while hiding the Severity and Thread fields
    from the displayed line.

.INPUTS
    None.

    This script does not accept pipeline input.

.OUTPUTS
    None.

    Parsed entries are written directly to the host using severity-based
    colors.

.NOTES
    Press Ctrl+C to stop monitoring the log.

    CMTrace type mapping:

        1 = Information
        2 = Warning
        3 = Error
#>

[CmdletBinding()]
param (
    [Parameter(
        Mandatory,
        Position = 0,
        HelpMessage = 'Enter the path to a CMTrace-formatted log file.'
    )]
    [ValidateNotNullOrEmpty()]
    [string]$LogFile,

    [Parameter()]
    [ValidateSet('All', 'Information', 'Warning', 'Error')]
    [string[]]$Type = 'All',

    [Parameter()]
    [ValidateRange(1, [int]::MaxValue)]
    [int]$Tail,

    [Parameter()]
    [scriptblock]$WhereObject,

    [Parameter()]
    [ValidateSet('Timestamp', 'Component', 'Severity', 'Thread', 'Message')]
    [string[]]$HideField = @()
)

if (-not (Test-Path -LiteralPath $LogFile -PathType Leaf)) {
    throw "Log file not found: $LogFile"
}

# Map CMTrace numeric types to readable severity names.
$typeMapping = @{
    '1' = 'Information'
    '2' = 'Warning'
    '3' = 'Error'
}

# Expected CMTrace line format:
# <![LOG[Message]LOG]!><time="..." date="..." component="..." ...>
$cmTracePattern = @'
^<!\[LOG\[(?<Message>.*?)\]LOG\]!><time="(?<Time>[^"]*)" date="(?<Date>[^"]*)" component="(?<Component>[^"]*)" context="(?<Context>[^"]*)" type="(?<Type>[^"]*)" thread="(?<Thread>[^"]*)" file="(?<File>[^"]*)">$
'@

$getContentParameters = @{
    LiteralPath = $LogFile
    Wait        = $true
}

if ($PSBoundParameters.ContainsKey('Tail')) {
    $getContentParameters.Tail = $Tail
}

# Returns the current console width, or 0 when output is redirected (piped
# or captured) and wrapping should be skipped.
function Get-ConsoleWidth {
    if ([Console]::IsOutputRedirected) {
        return 0
    }

    try {
        $width = $Host.UI.RawUI.WindowSize.Width
    } catch {
        return 0
    }

    if (-not $width -or $width -le 0) {
        return 0
    }

    return $width
}

# Writes a prefixed line, word-wrapping the message so continuation lines
# are indented to align under the message column instead of column 0.
function Write-WrappedHostLine {
    param (
        [string]$Prefix,
        [string]$Message,
        [string]$Color,
        [int]$Width
    )

    $minAvailableWidth = 20
    $available = $Width - $Prefix.Length

    if ($Width -le 0 -or $available -lt $minAvailableWidth) {
        Write-Host ($Prefix + $Message) -ForegroundColor $Color
        return
    }

    $words = $Message -split '\s+' | Where-Object { $_.Length -gt 0 }
    $lines = [System.Collections.Generic.List[string]]::new()
    $current = ''

    foreach ($word in $words) {
        $candidate = if ($current.Length -eq 0) { $word } else { "$current $word" }

        if ($candidate.Length -gt $available -and $current.Length -gt 0) {
            $lines.Add($current)
            $current = $word
        } else {
            $current = $candidate
        }
    }

    if ($current.Length -gt 0 -or $lines.Count -eq 0) {
        $lines.Add($current)
    }

    $indent = ' ' * $Prefix.Length

    for ($i = 0; $i -lt $lines.Count; $i++) {
        $linePrefix = if ($i -eq 0) { $Prefix } else { $indent }
        Write-Host ($linePrefix + $lines[$i]) -ForegroundColor $Color
    }
}

Get-Content @getContentParameters | ForEach-Object {
    $line = $_

    # Handle lines that are not in CMTrace format.
    if ($line -notmatch $cmTracePattern) {
        if (
            $Type -contains 'All' -and
            -not $PSBoundParameters.ContainsKey('WhereObject')
        ) {
            Write-Host $line -ForegroundColor DarkGray
        }

        return
    }

    $severity = $typeMapping[$Matches.Type]

    if (-not $severity) {
        $severity = 'Unknown'
    }

    # Apply the severity filter.
    if (
        $Type -notcontains 'All' -and
        $Type -notcontains $severity
    ) {
        return
    }

    # Create a structured object for filtering and display.
    $entry = [pscustomobject]@{
        Timestamp = '{0} {1}' -f $Matches.Date, $Matches.Time
        Date      = $Matches.Date
        Time      = $Matches.Time
        Component = $Matches.Component
        Context   = $Matches.Context
        Type      = $Matches.Type
        Severity  = $severity
        Thread    = $Matches.Thread
        File      = $Matches.File
        Message   = $Matches.Message
    }

    # Apply the custom Where-Object clause.
    if ($PSBoundParameters.ContainsKey('WhereObject')) {
        $filterResult = $entry |
            Where-Object -FilterScript $WhereObject

        if (-not $filterResult) {
            return
        }
    }

    # Build the displayed line last, so hiding a field never affects
    # filtering above, which always sees the full parsed entry.
    $visibleFields = [System.Collections.Generic.List[string]]::new()

    if ($HideField -notcontains 'Timestamp') {
        $visibleFields.Add("[$($entry.Timestamp)]")
    }

    if ($HideField -notcontains 'Component') {
        $visibleFields.Add("[$($entry.Component)]")
    }

    if ($HideField -notcontains 'Severity') {
        $visibleFields.Add("[$($entry.Severity)]")
    }

    if ($HideField -notcontains 'Thread') {
        $visibleFields.Add("[Thread:$($entry.Thread)]")
    }

    $prefix = if ($visibleFields.Count -gt 0) { ($visibleFields -join ' ') + ' ' } else { '' }
    $message = if ($HideField -contains 'Message') { '' } else { $entry.Message }

    $color = switch ($entry.Severity) {
        'Warning' { 'Yellow' }
        'Error'   { 'Red' }
        'Unknown' { 'DarkGray' }
        default   { 'Gray' }
    }

    Write-WrappedHostLine -Prefix $prefix -Message $message -Color $color -Width (Get-ConsoleWidth)
}
