<#
.SYNOPSIS
    Displays and follows a CMTrace-formatted log file.

.DESCRIPTION
    Reads a CMTrace-formatted log file, parses each entry, and displays it
    in a readable, color-coded format.

    After processing the existing lines, the script continues monitoring the
    file and displays new entries as they are written.

    CMTrace severity colors:

        Information = Gray
        Warning     = Yellow
        Error       = Red

.PARAMETER LogFile
    Specifies the path to the CMTrace-formatted log file.

    The file must exist when the script starts.

.PARAMETER Type
    Specifies the CMTrace severity types to display.

    Supported values:

        All
        Information
        Warning
        Error

    Multiple severity types can be provided by separating them with commas.

    The default value is All.

.PARAMETER Tail
    Specifies the number of existing physical lines to process when the
    script starts.

    After processing those lines, the script continues monitoring the file
    for new entries.

    If Tail is omitted, the entire existing log is processed.

    Tail is applied before parsing and filtering. For example, using
    "-Tail 100 -Type Error" examines the last 100 physical lines and displays
    only errors found within those lines.

.PARAMETER WhereObject
    Specifies an optional Where-Object filter script to apply to every parsed
    CMTrace entry.

    The current parsed entry is available through $_ and contains:

        Timestamp
        Date
        Time
        Component
        Context
        Type
        Severity
        Thread
        File
        Message

    Non-CMTrace lines are not displayed when WhereObject is specified.

.EXAMPLE
    .\Watch-CMTraceLog.ps1 `
        -LogFile 'C:\Windows\CCM\Logs\AppEnforce.log'

    Processes the entire existing log and follows new entries.

.EXAMPLE
    .\Watch-CMTraceLog.ps1 `
        -LogFile 'C:\Windows\CCM\Logs\AppEnforce.log' `
        -Tail 50

    Processes the last 50 physical lines and follows new entries.

.EXAMPLE
    .\Watch-CMTraceLog.ps1 `
        -LogFile 'C:\Windows\CCM\Logs\AppEnforce.log' `
        -Type Error

    Displays only error entries.

.EXAMPLE
    .\Watch-CMTraceLog.ps1 `
        -LogFile 'C:\Windows\CCM\Logs\AppEnforce.log' `
        -Tail 100 `
        -Type Warning, Error

    Examines the last 100 lines and displays warnings and errors.

.EXAMPLE
    .\Watch-CMTraceLog.ps1 `
        -LogFile 'C:\Windows\CCM\Logs\AppEnforce.log' `
        -WhereObject { $_.Component -eq 'AppEnforce' }

    Displays entries generated by the AppEnforce component.

.EXAMPLE
    .\Watch-CMTraceLog.ps1 `
        -LogFile 'C:\Windows\CCM\Logs\AppEnforce.log' `
        -WhereObject { $_.Message -match 'failed|error|exception' }

    Displays entries whose message matches the supplied regular expression.

.EXAMPLE
    .\Watch-CMTraceLog.ps1 `
        -LogFile 'C:\Windows\CCM\Logs\AppEnforce.log' `
        -Tail 500 `
        -WhereObject {
            $_.Severity -in 'Warning', 'Error' -and
            $_.Message -match 'install'
        }

    Displays warning and error entries containing "install" from the last
    500 lines and from new entries written afterward.

.INPUTS
    None.

    This script does not accept pipeline input.

.OUTPUTS
    None.

    Parsed entries are written directly to the host using severity-based
    colors.

.NOTES
    Press Ctrl+C to stop monitoring the log.

    CMTrace type mapping:

        1 = Information
        2 = Warning
        3 = Error
#>

[CmdletBinding()]
param (
    [Parameter(
        Mandatory,
        Position = 0,
        HelpMessage = 'Enter the path to a CMTrace-formatted log file.'
    )]
    [ValidateNotNullOrEmpty()]
    [string]$LogFile,

    [Parameter()]
    [ValidateSet('All', 'Information', 'Warning', 'Error')]
    [string[]]$Type = 'All',

    [Parameter()]
    [ValidateRange(1, [int]::MaxValue)]
    [int]$Tail,

    [Parameter()]
    [scriptblock]$WhereObject
)

if (-not (Test-Path -LiteralPath $LogFile -PathType Leaf)) {
    throw "Log file not found: $LogFile"
}

# Map CMTrace numeric types to readable severity names.
$typeMapping = @{
    '1' = 'Information'
    '2' = 'Warning'
    '3' = 'Error'
}

# Expected CMTrace line format:
# <![LOG[Message]LOG]!><time="..." date="..." component="..." ...>
$cmTracePattern = @'
^<!\[LOG\[(?<Message>.*?)\]LOG\]!><time="(?<Time>[^"]*)" date="(?<Date>[^"]*)" component="(?<Component>[^"]*)" context="(?<Context>[^"]*)" type="(?<Type>[^"]*)" thread="(?<Thread>[^"]*)" file="(?<File>[^"]*)">$
'@

$getContentParameters = @{
    LiteralPath = $LogFile
    Wait        = $true
}

if ($PSBoundParameters.ContainsKey('Tail')) {
    $getContentParameters.Tail = $Tail
}

Get-Content @getContentParameters | ForEach-Object {
    $line = $_

    # Handle lines that are not in CMTrace format.
    if ($line -notmatch $cmTracePattern) {
        if (
            $Type -contains 'All' -and
            -not $PSBoundParameters.ContainsKey('WhereObject')
        ) {
            Write-Host $line -ForegroundColor DarkGray
        }

        return
    }

    $severity = $typeMapping[$Matches.Type]

    if (-not $severity) {
        $severity = 'Unknown'
    }

    # Apply the severity filter.
    if (
        $Type -notcontains 'All' -and
        $Type -notcontains $severity
    ) {
        return
    }

    # Create a structured object for filtering and display.
    $entry = [pscustomobject]@{
        Timestamp = '{0} {1}' -f $Matches.Date, $Matches.Time
        Date      = $Matches.Date
        Time      = $Matches.Time
        Component = $Matches.Component
        Context   = $Matches.Context
        Type      = $Matches.Type
        Severity  = $severity
        Thread    = $Matches.Thread
        File      = $Matches.File
        Message   = $Matches.Message
    }

    # Apply the custom Where-Object clause.
    if ($PSBoundParameters.ContainsKey('WhereObject')) {
        $filterResult = $entry |
            Where-Object -FilterScript $WhereObject

        if (-not $filterResult) {
            return
        }
    }

    $formattedLine = '[{0}] [{1}] [{2}] [Thread:{3}] {4}' -f `
        $entry.Timestamp,
        $entry.Component,
        $entry.Severity,
        $entry.Thread,
        $entry.Message

    $color = switch ($entry.Severity) {
        'Warning' { 'Yellow' }
        'Error'   { 'Red' }
        'Unknown' { 'DarkGray' }
        default   { 'Gray' }
    }

    Write-Host $formattedLine -ForegroundColor $color
}
